apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: gcr.io/xs-amiable-bonus-6/django-image:1.2
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secret-password"
        - name: DJANGO_SETTINGS_MODULE
          value: "project.settings.prod"
        ports:
        - containerPort: 8000
