sudo: required

language: python

services:
  - docker

install:
  - docker-compose -f docker-compose.yml build react

script:
  - docker-compose -f docker-compose.yml run react npm run test
  - docker-compose -f docker-compose.yml run react npm run lint
