version: '2'
services:
    django:
        extends:
            file: common.yml
            service: django
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret-password
        volumes:
            - static:/srv/django/static
        links:
            - postgres:postgres
            - rabbitmq:rabbitmq
            - redis:redis

    celery:
        image: django-image
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret-password
        links:
            - postgres:postgres
            - rabbitmq:rabbitmq
            - redis:redis
        command: celery -A project worker -l warning

    nginx:
        build: ./nginx
        links:
            - django:django
        volumes_from:
            - django

    react:
        build: ./react

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret-password

    redis:
        image: redis:3.2

    rabbitmq:
        image: rabbitmq:3.6
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

volumes:
    static: {}
