django:
    build: ./django
    volumes:
        - ./django/src:/srv/django
    expose:
        - "8000"
    environment:
        DJANGO_SETTINGS_MODULE: project.settings.dev
    links:
        - db:db

nginx:
    build: ./nginx
    ports:
        - "8080:80"
    links:
        - django:django
    volumes_from:
        - django

react:
    build: ./react
    volumes:
        - ./react/src:/srv/react
    ports:
        - "8000:8000"
    links:
        - nginx:nginx

db:
    image: postgres
