django:
    build: ./django
    volumes:
        - ./django/src:/srv/django
    expose:
        - "8000"
    environment:
        DJANGO_SETTINGS_MODULE: project.settings.dev
    links:
        - db:db
        - rabbitmq:rabbitmq

celery:
    build: ./django
    volumes_from:
        - django
    expose:
        - "8000"
    environment:
        DJANGO_SETTINGS_MODULE: project.settings.dev
    links:
        - db:db
        - rabbitmq:rabbitmq
    command: ./manage.py celery worker -l info

nginx:
    build: ./nginx
    ports:
        - "8080:80"
    links:
        - django:django
    volumes_from:
        - django

react:
    build: ./react
    volumes:
        - ./react/src:/srv/react
    ports:
        - "8000:8000"
    links:
        - nginx:nginx

db:
    image: postgres

rabbitmq:
    image: rabbitmq:3.6
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
