version: '2'
services:
    django:
        extends:
            file: common.yml
            service: django
        volumes:
            - static:/srv/django/static
        links:
            - db:db
            - rabbitmq:rabbitmq

    celery:
        image: django-image
        links:
            - db:db
            - rabbitmq:rabbitmq
        command: celery -A project worker -l warning

    nginx:
        build: ./nginx
        links:
            - django:django
        volumes_from:
            - django

    react:
        build: ./react

    db:
        image: postgres

    rabbitmq:
        image: rabbitmq:3.6
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

volumes:
    static: {}
