apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: gcr.io/xs-amiable-bonus-6/django-image
        command: ["/usr/local/bin/entrypoint", "celery", "-A", "project", "worker", "-l", "warning"]
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secret-password"
        - name: DJANGO_SETTINGS_MODULE
          value: "project.settings.prod"
