apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: django-tls
    hosts:
    - www.mhelmer.se
  rules:
  - host: www.mhelmer.se
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-django
          servicePort: 80
