apiVersion: v1
kind: Service
metadata:
  name: nginx-django
  labels:
    app: nginx-django
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: nginx-django
