apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-django-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-django
    spec:
      containers:
      - name: nginx-django
        image: gcr.io/xs-amiable-bonus-6/django-nginx:1.2
        ports:
        - containerPort: 80
